# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#news'
    weight: 10
  - name: Events
    url: '#events'
    weight: 20
  - name: Members
    url: '#people'
    weight: 35
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Talks
    url: '#talk'
    weight: 30
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
